name = "twitch-helix"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]


[observability]
[observability.logs]
enabled = true
invocation_logs = true

[[kv_namespaces]]
binding = "TWITCH_KV"
id = "fluke_twitch_kv"